include /etc/nginx/xff.inc;

server {
    listen 80;
    server_name nginx1;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $clean_x_forwarded_for;
        proxy_pass http://app:3000;
    }

    # пользователь -> nginx1 -> nginx2 -> приложение
    location /to-nginx2/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $clean_x_forwarded_for;
        proxy_pass http://nginx2/;
    }

    # пользователь -> nginx1 -> nginx2 -> nginx3 -> приложение
    location /to-nginx2-nginx3/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $clean_x_forwarded_for;
        proxy_pass http://nginx2/to-nginx3/;
    }

    # пользователь -> nginx1 -> nginx3 -> приложение
    location /to-nginx3/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $clean_x_forwarded_for;
        proxy_pass http://nginx3/;
    }
}
